{{- include "argus.validate" . -}}
{{- if .Values.server.enabled -}}
{{- if not .Values.auth.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-server" (include "argus.fullname" .) }}
  labels:
    {{- include "argus.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.auth.jwtSecret | quote }}
  ADMIN_PASSWORD: {{ .Values.auth.adminPassword | quote }}
  {{- if .Values.auth.sidecarLinkToken }}
  SIDECAR_LINK_TOKEN: {{ .Values.auth.sidecarLinkToken | quote }}
  {{- end }}
  {{- if .Values.externalDatabase.url }}
  DATABASE_URL: {{ .Values.externalDatabase.url | quote }}
  {{- end }}
  {{- if .Values.externalRedis.url }}
  REDIS_URL: {{ .Values.externalRedis.url | quote }}
  {{- end }}
{{- end }}
{{- end }}
