import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useResolvedTheme } from '../lib/theme';
import { cn } from '../lib/utils';

/**
 * Render HTML content inside a locked-down iframe. Inline CSS still
 * applies, so a static page renders the way the author intended; any
 * external resources (CDN scripts, cross-origin images) won't load —
 * that's the trade-off we accept for previewing untrusted content
 * (either pulled off a remote agent's working tree, or generated by
 * the model in a chat code block).
 *
 * Sandbox posture is keyed off `autoHeight`:
 *  - default (`autoHeight=false`, the FileViewer path): `sandbox=""`
 *    (empty value). Unique opaque origin, no scripts, no forms, no
 *    navigation — the strictest setting. The parent CANNOT read the
 *    iframe's document, so it's sized by its container (`h-full`).
 *  - `autoHeight=true` (the chat code-block path): `sandbox=
 *    "allow-same-origin"`. Still NO `allow-scripts`, so no JavaScript
 *    in the document runs — but the iframe shares our origin just
 *    enough that the parent can read `scrollHeight` and grow the
 *    frame to fit. Granting same-origin *without* scripts is safe:
 *    there's no script in the frame to abuse the same-origin access.
 *
 * Theme handling: a plain HTML page (no body bg, no styles) inherits
 * UA defaults — black text on white. Hard to read on the dashboard's
 * dark theme, and pure-white iframe-bg-on-dark-app is jarring too.
 * We inject a `:root { color-scheme }` style matching the dashboard's
 * resolved theme, so the iframe's UA defaults flip to dark text/bg
 * when the dashboard is dark. Pages that declare their own colors
 * still win — color-scheme only affects UA defaults, not authored CSS.
 */
export function HtmlPreview({
  content,
  name,
  className,
  autoHeight = false,
}: {
  content: string;
  name: string;
  className?: string;
  autoHeight?: boolean;
}) {
  const theme = useResolvedTheme();
  const srcDoc = useMemo(() => injectColorScheme(content, theme), [content, theme]);
  const iframeRef = useRef<HTMLIFrameElement>(null);
  const [height, setHeight] = useState<number | null>(null);

  const measure = useCallback(() => {
    const doc = iframeRef.current?.contentDocument;
    if (!doc) return;
    const next = Math.max(
      doc.body?.scrollHeight ?? 0,
      doc.documentElement?.scrollHeight ?? 0,
    );
    if (next <= 0) return;
    // Guard the ResizeObserver feedback loop: only commit a real change.
    setHeight((prev) => (prev != null && Math.abs(prev - next) <= 1 ? prev : next));
  }, []);

  useEffect(() => {
    if (!autoHeight) return;
    const iframe = iframeRef.current;
    if (!iframe) return;
    let ro: ResizeObserver | null = null;
    const onLoad = () => {
      measure();
      const doc = iframe.contentDocument;
      if (doc?.documentElement && typeof ResizeObserver !== 'undefined') {
        // Re-measure when the content reflows — <details> expanding,
        // a :checked view-switcher swapping cards, fonts settling, etc.
        ro = new ResizeObserver(() => measure());
        ro.observe(doc.documentElement);
      }
    };
    iframe.addEventListener('load', onLoad);
    // srcDoc may already be parsed by the time this effect runs.
    if (iframe.contentDocument?.readyState === 'complete') onLoad();
    return () => {
      iframe.removeEventListener('load', onLoad);
      ro?.disconnect();
    };
    // `srcDoc` in deps: a theme flip / streaming update reloads the
    // frame, so we must rebind the load listener and re-measure.
  }, [autoHeight, srcDoc, measure]);

  return (
    <iframe
      ref={iframeRef}
      title={name}
      srcDoc={srcDoc}
      sandbox={autoHeight ? 'allow-same-origin' : ''}
      className={cn(autoHeight ? 'block w-full border-0' : 'h-full w-full', className)}
      style={autoHeight && height != null ? { height } : undefined}
    />
  );
}

/**
 * Insert a `<style>:root{color-scheme:…}</style>` into the user's
 * HTML so the iframe's UA defaults follow the dashboard theme. We try
 * to land it inside an existing `<head>`; failing that, after `<html>`;
 * and as a final fallback, wrap the input in a minimal standards-mode
 * document. Wrapping is the right call for body fragments — leaving
 * the input doctype-less would put the iframe in quirks mode.
 */
function injectColorScheme(content: string, theme: 'light' | 'dark'): string {
  const style = `<style>:root{color-scheme:${theme}}</style>`;
  if (/<head\b[^>]*>/i.test(content)) {
    return content.replace(/<head\b[^>]*>/i, (m) => m + style);
  }
  if (/<html\b[^>]*>/i.test(content)) {
    return content.replace(/<html\b[^>]*>/i, (m) => `${m}<head>${style}</head>`);
  }
  return `<!DOCTYPE html><html><head>${style}</head><body>${content}</body></html>`;
}
